[Вопросы](README.md)

# Обработка исключений

+ [Что такое Exception ?](#что-такое-exception-)
+ [Типы исключений](#типы-исключений)
+ [Для чего служат try, catch, finally ?](#для-чего-служат-try-catch-finally-)
+ [Что такое call stack ?](#что-такое-call-stack-)
+ [В чём разница между throw и throw ex ?](#в-чём-разница-между-throw-и-throw-ex-)

## Что такое Exception ?
**Exception** (исключение) - это объект, который представляет ошибку или исключительную ситуацию, возникшую во время выполнения программы. Когда возникает исключение, выполнение текущего потока прерывается, и поиск исключения начинается в стеке вызовов, пока не будет найден обработчик исключения или программа завершится.

В языке программирования C# и в .NET Framework, исключения представлены классом System.Exception. Все исключения в C# являются производными от этого базового класса.

Ряд свойств, с помощью которых можно получить информацию об исключении:

- **InnerException**: хранит информацию об исключении, которое послужило причиной текущего исключения

- **Message**: хранит сообщение об исключении, текст ошибки

- **Source**: хранит имя объекта или сборки, которое вызвало исключение

- **StackTrace**: возвращает строковое представление стека вызывов, которые привели к возникновению исключения

- **TargetSite**: возвращает метод, в котором и было вызвано исключение

## Типы исключений
Также есть более специализированные типы исключений, которые предназначены для обработки каких-то определенных видов исключений. Их довольно много, вот некоторые:

- DivideByZeroException: представляет исключение, которое генерируется при делении на ноль

- ArgumentOutOfRangeException: генерируется, если значение аргумента находится вне диапазона допустимых значений

- ArgumentException: генерируется, если в метод для параметра передается некорректное значение

- IndexOutOfRangeException: генерируется, если индекс элемента массива или коллекции находится вне диапазона допустимых значений

- InvalidCastException: генерируется при попытке произвести недопустимые преобразования типов

- NullReferenceException: генерируется при попытке обращения к объекту, который равен null (то есть по сути неопределен)

И при необходимости мы можем разграничить обработку различных типов исключений, включив дополнительные блоки catch:
```
static void Main(string[] args)
{
    try
    {
        int[] numbers = new int[4];
        numbers[7] = 9;     // IndexOutOfRangeException
 
        int x = 5;
        int y = x / 0;  // DivideByZeroException
        Console.WriteLine($"Результат: {y}");
    }
    catch (DivideByZeroException)
    {
        Console.WriteLine("Возникло исключение DivideByZeroException");
    }
    catch (IndexOutOfRangeException ex)
    {
        Console.WriteLine(ex.Message);
    }
             
    Console.Read();
}
```
В данном случае блоки catch обрабатывают исключения типов IndexOutOfRangeException и DivideByZeroException

## Для чего служат try, catch, finally ?
При выполнении программы возникают ошибки, которые трудно предусмотреть или предвидеть, а иногда и вовсе невозможно. Например, при передачи файла по сети может неожиданно оборваться сетевое подключение. такие ситуации называются **исключениями**. Язык C# предоставляет разработчикам возможности для обработки таких ситуаций. Для этого в C# предназначена конструкция **try...catch...finally**.

При использовании блока try...catch..finally вначале выполняются все инструкции в блоке try. Если в этом блоке не возникло исключений, то после его выполнения начинает выполняться блок finally. И затем конструкция try..catch..finally завершает свою работу.

Если же в блоке try вдруг возникает исключение, то обычный порядок выполнения останавливается, и среда CLR начинает искать блок catch, который может обработать данное исключение. Если нужный блок catch найден, то он выполняется, и после его завершения выполняется блок finally.

Если нужный блок catch не найден, то при возникновении исключения программа аварийно завершает свое выполнение.

## Что такое call stack ?
Часть памяти компьютера отведена под стек.

Call Stack - окно, в котором отображаются все уровни вложенности вызовов функций.
Там вы можете узнать, в какой функции вы сейчас находитесь, из какой функции она была вызвана и так далее рекурсивно наверх вплоть до точки входа в программу.
Собственно call stack вычисляется на основе информации из стека.

Стек вызовов или call stack — это список всех активных функций, которые вызывались, до текущей точки выполнения. В стеке вызовов отображается каждая вызываемая функция, а также строка, которая в данный момент выполняется в программе. Всякий раз, при вызове новой функции - она добавляется в самый top of call stack

## [В чём разница между throw и throw ex ?](https://dev-station.ru/categories/csharp/cheatsheet/csharp-base-cheatsheet#3395)
**throw** повторно выбрасывает исключение (re-throw), которое было обнаружено, и сохраняет трассировку стека (путь к источнику исключения). [информация об исключении сохраняется, и трассировка стека будет содержать информацию о точном месте, где было возбуждено исключение, включая все промежуточные вызовы]

**throw ex** генерирует одно и то же исключение, но сбрасывает трассировку стека на метод, где делается throw ex. [теряется информацию о точном источнике исключения.]